builds:
- binary: uptimerobot-exporter
- env:
  - CGO_ENABLED=0
  # Set flags for custom build tags.
  # Default is empty.
- flags:
  - ldflags:
    - -w -s
>>>>>>> Disable debug symbols
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  files:
    - LICENSE
    - MAINTAINERS.md
    - README.md
    - grafana
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
