go:
    cgo: false
verbose: true
repository:
    path: github.com/masaruhoshi/uptimerobot-prometheus-exporter    
build:
    prefix: .
    binaries:
        - name: uptimerobot-exporter
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X main.Version={{.Version}}
        -X main.Revision={{.Revision}}
        -X main.Branch={{.Branch}}
        -X main.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - MAINTAINERS.md
        - README.md
        - grafana
crossbuild:
    platforms:
        - darwin/amd64
        - linux/amd64   
        # - linux/386
