language: go

go:
  - 1.8.x
  - tip

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
