[[constraint]]
  name = "github.com/masaruhoshi/uptimerobot-go.v2"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
