scrape_configs:

- job_name: 'Uptimerobot'
  scrape_interval: 1m
  scrape_timeout: 30s
  static_configs:
    - targets:
      - 'uptimerobot-exporter:9429'
  params:
    collect[]:
      - global_status